---
mongodb_host: 'localhost'

mongodb_port: 27017

mongodb_credentials:

mongodb_options:

frequency: 10

threshold_timeout: 60

triggers:
  mongodb:
    threshold: 5
    database: mongoop
    collection: history

  nsca:
    treshold: 5
    monitoring_server: nagios.foo.com
    service: mongoop

  nsca:
    treshold: 60
    monitoring_server: nagios.foo.com
    service: mongoop
    status: critical

  email:
    treshold: 60
    subject: 'Mongoop report'
    from: 'mongoop@localhost'
    to: 'root'
    smtp_host: 'localhost'

  sentry:
    threshold: 80
    dsn: 'https://898weqe899qweqeq8:wqeqw8888@app.getsentry.com/76885'
    message: 'mongoop slow operation :: {opid}'
    level: info

  killer:
    treshold: 120
