---
mongodb_host: 'localhost'

mongodb_port: 27017

mongodb_credentials:

mongodb_options:

frequency: 10

threshold_timeout: 60

op_triggers: []

balancer_triggers: []

# op_triggers:
#   trigger_mongodb_1:
#     type: mongodb
#     threshold: 5
#     state: True
#     params:
#       database: mongoop
#       collection: history
# 
#   trigger_email_xxx:
#     type: email
#     threshold: 60
#     state: True
#     params:
#       subject: 'Mongoop report'
#       from: 'mongoop@localhost'
#       to: 'root'
#       smtp_host: 'localhost'
# 
#   foo_bar_sentry:
#     type: sentry
#     threshold: 80
#     state: True
#     params:
#       dsn: 'https://898weqe899qweqeq8:wqeqw8888@app.getsentry.com/76885'
#       message: 'mongoop slow operation :: {opid}'
#       level: info
# 
#   foo_killer:
#     type: killer
#     threshold: 120
#     state: True
# 
#   webhook_trigger:
#     threshold: 240
#     state: True
#     params:
#       method: get
#       url: https://httpbin.org/get
#       http_params:
#         show_env: 1
#       requests_params:
#         verify: False
#
#   graphite_trigger:
#      threshold: 500
#      state: True
#      params:
#        metric_per_ns: True
#        graphitesend_params:
#          prefix: mongoop.slow_op
#          system_name: ''
# 
# balancer_triggers:
#   webhook:
#     state: True
#     params:
#       method: get
#       url: https://httpbin.org/get
#       http_params:
#         show_env: 1
#       requests_params:
#         verify: False
# 
#   webhook_nok:
#     state: False
#     params:
#       method: get
#       url: https://httpbin.org/get
#       http_params:
#         show_env: 1
#       requests_params:
#         verify: False
